config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "refuels#index"
  resources :refuels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/refuel.rb
class Refuel < ApplicationRecord
  belongs_to :user

  validates :date, :odometer, :volume, :user_id, presence: true
  validates :odometer, :volume, numericality: { greater_than: 0.0 }

  validate :price_and_cost, if: :volume
  validate :odometer_and_date

  def traveled
    previous = previous_full_refuel
    self.odometer - previous.odometer if previous
  end
  def filled_volume
    filled = self.volume
    previous = previous_refuel
    unless previous.nil? || previous.full
      filled += previous.filled_volume
    end
    return filled
  end

  def consumption
    if previous_refuel && previous_refuel.full
      trav = traveled 
      return (trav && full) ? (100 * filled_volume / trav) : nil
    end
  end

 private

  # price or cost calculation
  def price_and_cost
    if price
      self.cost = price * volume
    elsif cost
      self.price = cost / volume
    end
  end

  # Check odometer and date consistency
  def odometer_and_date
    previous = previous_refuel
    errors.add :base, "Verifique la fecha" if previous && previous.date > date
    return errors.empty?
  end

  # Return previous refuel
  def previous_refuel
    Refuel.where(user_id: self.user_id).where("odometer < ?", self.odometer).order(:odometer).last
  end
  # Return previous full refuel
  def previous_full_refuel
    Refuel.where(user_id: self.user_id, full: true).where("odometer < ?", self.odometer).order(:odometer).last
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  has_many :refuels

  validates :name, :email, presence: true

  enum rol: [:user, :admin]
  after_initialize :set_default_rol, if: :new_record?

  def admin?
    rol == 'admin'
  end

  def total_odometer full=false
    total = 0.0
    last_ref = full ? refuels.where(full: true).order(:odometer).last : refuels.order(:odometer).last
    if last_ref && refuels.count > 1
      total = last_ref.odometer - refuels.order(:odometer).first.odometer
    end
    return total
  end

  def total_volume full=false
    first_ref = refuels.order(:odometer).first
    last_ref = full ? refuels.where(full: true).order(:odometer).last : refuels.order(:odometer).last
    return refuels.where("odometer > ? AND odometer <= ?", first_ref.odometer, last_ref.odometer).sum(:volume) if first_ref && last_ref
  end

 private

  def set_default_rol
    self.rol ||= :user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :user_permitted_parameters, if: :devise_controller?

 private

  def user_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/refuels_controller.rb
class RefuelsController < ApplicationController
  before_action :set_refuel, only: [:show, :edit, :update, :destroy]

  # GET /refuels
  # GET /refuels.json
  def index
    @refuels = current_user.refuels.order("date desc")
    total_volume = current_user.total_volume
    total_odometer = current_user.total_odometer
    total_full_volume = current_user.total_volume(true) || 0.0
    total_full_odometer = current_user.total_odometer(true)
    @totals = { volume: total_volume,
                odometer: total_odometer,
                consumption: total_full_odometer.blank? ? 0.0 : 100 * total_full_volume / total_full_odometer }
  end

  # GET /refuels/1
  # GET /refuels/1.json
  def show
  end

  # GET /refuels/new
  def new
    @refuel = Refuel.new 
  end

  # GET /refuels/1/edit
  def edit
  end

  # POST /refuels
  # POST /refuels.json
  def create
    @refuel = Refuel.new(refuel_params)
    @refuel.user_id = current_user.id 
    if @refuel.save
      redirect_to refuels_path
    else
      render :new
    end
  end

  # PATCH/PUT /refuels/1
  # PATCH/PUT /refuels/1.json
  def update
  end

  # DELETE /refuels/1
  # DELETE /refuels/1.json
  def destroy
    @refuel.destroy
    respond_to do |format|
      format.html { redirect_to refuels_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end


 private

  # Use callbacks to share common setup or constraints between actions.
  def set_refuel
    @refuel = Refuel.find_by_id params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def refuel_params
    params.require(:refuel).permit(:date, :odometer, :volume, :cost, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/refuels_helper.rb
module RefuelsHelper
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <a href="https://github.com/Sitiodistinto/gas">Gas Code</a>
  </div>
  <strong>
    Copyleft © 2017-2022
    <a href="https://github.com/Sitiodistinto/" target="_blank"> SitioDistinto punto Net</a>
  </strong>
  Some rights reserved.
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <a class="logo" href="/">
    Gas App
  </a>
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <%= render partial: "layouts/user_information" %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
        <% unless notice.blank? %>
          <div>
            <!-- Notice row -->
            <div class="row">
              <div class="col-md-12">
                <div class="box box-success">
                  <div class="box-header with-border">
                    <h3 class="box-title"><%= notice %></h3>
                    <div class="box-tools pull-right">
                      <button type="button" class="btn btn-box-tool" data-widget="remove">
                        <i class="fa fa-times"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.row -->
          </div>
        <% end %>
        <% unless alert.blank? %>
          <div>
            <!-- Alert row -->
            <div class="row">
              <!-- Left col -->
              <div class="col-md-12">
                <div class="box box-danger">
                  <div class="box-header with-border">
                    <h3 class="box-title"><%= alert %></h3>
                    <div class="box-tools pull-right">
                      <button type="button" class="btn btn-box-tool" data-widget="remove">
                        <i class="fa fa-times"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.row -->
          </div>
        <% end %>

app/views/layouts/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <% if user_signed_in? %>
      <div class="user-panel">
        <div class="pull-left image">
          <%= image_tag 'user-avatar.160x160.png', class: 'img-circle', alt: t('User image') %>
        </div>
        <div class="pull-left info">
          <p><%= current_user.name %></p>
          <a href="#">
            <i class="fa fa-circle text-success">
            </i>Online
            </a>
        </div>
      </div>
      <form action="#" class="sidebar-form" method="get">
        <div class="input-group">
          <input class="form-control" name="q" placeholder="Search..." type="text" />
          <span class="input-group-btn">
          <button class="btn btn-flat" id="search-btn" name="search" type="submit">
          <i class="fa fa-search">
          </i></button></span>
        </div>
      </form>
      <%= render partial: "layouts/sidebar_menu" %>
    <% end %>
  </section>
</aside>

app/views/layouts/_sidebar_menu.html.erb
      <ul class="sidebar-menu">
        <li class="header">
          HEADER
        </li>
        <li class="active">
          <a href="#">
        <span>Link</span>
        </a>
        </li>
        <li>
          <a href="#">
          <span>Another Link</span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <span>Multilevel</span>
            <i class="fa fa-angle-left pull-right">
            </i></a>
          <ul class="treeview-menu">
            <li>
              <a href="#"> Link in level 2</a>
            </li>
            <li>
              <a href="#"> Link in level 2</a>
            </li>
          </ul>
        </li>
      </ul>

app/views/layouts/_user_information.html.erb
        <!-- User Start -->
        <li class="dropdown user user-menu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= image_tag 'user-avatar.160x160.png', class: 'user-image', alt: t('User image') %>
          <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag 'user-avatar.160x160.png', class: 'img-circle', alt: t('User image') %>
              <p>
              <%= current_user.name %> <%= "<#{current_user.email}>" %>
                <small><%= I18n.t("layout.user.since")%[I18n.l(current_user.created_at.to_date, format: :long)] %></small>
              </p>
            </li>
            <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#"> Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#"> Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#"> Friends</a>
              </div>
            </li>
            <li class="user-footer">
              <div class="pull-left">
                <a class="btn btn-default btn-flat" href="#"><%= I18n.t("layout.user.my-profile") %></a>
              </div>
              <div class="pull-right">
                <%= link_to I18n.t("layout.user.sign-out"), destroy_user_session_path, method: :delete, class: "btn btn-default btn-flat" %>
              </div>
            </li>
          </ul>
        </li>
        <!-- User End -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Gas</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body class="fixed skin-blue-light">
    <div class="wrapper">
      <%= render "layouts/header" %>
      <%= render "layouts/sidebar" %>
      <div class="content-wrapper">
        <section class="content-header">
        </section>
        <section class="content">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </section>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/refuels/_form.html.erb
<%= form_for( @refuel ) do |f| %>
  <div class="form-group">
    <%= f.date_field :date, value: @refuel.date||Date.current, placeholder: I18n.t("activerecord.attributes.refuel.date"), class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.number_field :odometer, placeholder: I18n.t("activerecord.attributes.refuel.odometer"), class: "form-control", step: 1, required: true %>
  </div>
  <div class="form-group">
    <%= f.number_field :volume, placeholder: I18n.t("activerecord.attributes.refuel.volume"), class: "form-control", step: 0.001, required: true %>
  </div>
  <div class="form-group">
    <%= f.number_field :price, placeholder: I18n.t("activerecord.attributes.refuel.price"), class: "form-control", step: 0.001 %>
  </div>
  <div class="form-group">
    <%= f.number_field :cost, placeholder: I18n.t("activerecord.attributes.refuel.cost"), class: "form-control", step: 0.01 %>
  </div>
  <div class="form-group">
    <%= f.label :full %>
    <%= f.check_box :full %>
  </div>

  <div class="box-footer clearfix actions">
    <%= f.submit I18n.t("layout.save"), class: "btn btn-flat btn-sm btn-success pull-right" %>
  </div>
<% end -%>

app/views/refuels/index.html.erb
  <!-- Main row -->
  <% translation_scope = "activerecord.attributes.refuel" %>
  <div class="row">
    <!-- Left col -->
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= I18n.t("layout.latest-refuels") %></h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
              <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove">
              <i class="fa fa-times"></i>
            </button>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="table-responsive">
            <table class="table no-margin table-hover">
              <thead>
                <tr>
                  <th><%= I18n.t(:date, scope: translation_scope) %></th>
                  <th class="text-right"><%= I18n.t(:odometer, scope: translation_scope) %></th>
                  <th class="text-right"><%= I18n.t(:volume, scope: translation_scope) %></th>
                  <th class="text-right"><%= I18n.t(:price, scope: translation_scope) %></th>
                  <th class="text-right"><%= I18n.t(:cost, scope: translation_scope) %></th>
                  <th class="text-right"><%= I18n.t(:consumption, scope: translation_scope) %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <!-- Refuelings -->
                <% show_delete = true %>
                <% @refuels.each do |refuel| %>
                  <% consumption = refuel.consumption %>
                  <% color = case
                             when consumption.blank?
                               ""
                             when (consumption - @totals[:consumption]) > (0.05 * @totals[:consumption])
                               "danger"
                             when (consumption - @totals[:consumption]) < (0.05 * @totals[:consumption])
                               "success"
                             else
                               ""
                             end %>
                  <tr id="refuel-<%= refuel.id %>" class="<%= color %>">
                    <td title="<%= I18n.t( (refuel.full ? :full : :partial), scope: translation_scope) %>">
                      <%= I18n.l(refuel.date) %>
                    </td>
                    <td class="text-right"><%= refuel.odometer.to_i %></td>
                    <td class="text-right"><%= sprintf( "%0.02f", refuel.volume ) %></td>
                    <td class="text-right"><%= sprintf( "%0.03f", refuel.price ) %></td>
                    <td class="text-right"><%= sprintf( "%0.02f", refuel.cost ) %></td>
                    <td class="text-right"><%= sprintf( "%0.02f", consumption ) if consumption %></td>
                    <td class="text-right">
                      <% if show_delete -%>
                        <%= link_to content_tag("i", "", class: "fa fa-trash-o"),
                                      refuel_path(refuel),
                                      method: :delete,
                                      data: { confirm: I18n.t("layout.destroy-confirmation") } %>
                        <% show_delete = false -%>
                      <% end -%>
                    </td>
                  </tr>
                <% end %>
                <!-- Average -->
                <tfoot>
                  <tr id="refuel-totals" style="font-weight:bold;">
                    <td>TOTAL</td>
                    <td class="text-right"><%= @totals[:odometer].to_i %></td>
                    <td class="text-right"><%= @totals[:volume] %></td>
                    <td></td>
                    <td></td>
                    <td class="text-right"><%= sprintf( "%0.02f", @totals[:consumption]) %></td>
                    <td></td>
                  </tr>
                </tfoot>
              </tbody>
            </table>
          </div>
        <!-- /.table-responsive -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <%= link_to I18n.t("layout.new-refuel"), new_refuel_path, class: "btn btn-sm btn-info btn-flat pull-left" %>
        </div>
      <!-- /.box-footer -->
      </div>
    <!-- /.box -->
    </div>
  <!-- /.col -->
  </div>

app/views/refuels/new.html.erb
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><%= I18n.t("layout.new-refuel") %></h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
              <i class="fa fa-minus"></i>
            </button>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <%= render partial: "form" %>
        </div>
        <!-- /.box-body -->
      </div>
    <!-- /.box -->
    </div>
  <!-- /.col -->
  </div>